### ISSUE TITLE
Define claims order by entity type

### ISSUE THREAD

**Issue by jmformenti** [PhiloBiblon/philobiblon-ui#10]
We have a general order for an item defined in the following wiki page: https://philobiblon.cog.berkeley.edu/wiki/MediaWiki:Wikibase-SortedProperties
So we have a definition like (based on item type there is a different order, this is new):

```
==== Institutions ====
* P2 (Instance of)
* P476 (PhiloBiblon ID)
* P34 (Name history)
* P137 (History)
...
==== Library ====
* P2 (Instance of)
* P476 (PhiloBiblon ID)
* P34 (Naming)
* P111 (Address in Words)
...
==== Ms_Ed ====
* P2 (Instance of)
* P476 (PhiloBiblon ID)
* P73 (Note)
...
```

The current implementation (https://github.com/PhiloBiblon/philobiblon-ui/blob/master/frontend/service/wikibase.service.js#L45) does not take into account that the order for "Institutions" is different than for "Library" for example.
Additionally we need to order the qualifiers related to a claim, also defined in the `Wikibase-SortedProperties` page.

**Definition of Done**
* Extend current implementation to account for order based on item type.
* Order qualifiers within a claim accordingly.

**Comment by austininseoul** [comment]
If you can define an order for Library or Person, then I can add this to our code. I don't have permission to edit this on the wikibase.
