### ISSUE TITLE
Searching MAN, COP, and ANA

### ISSUE THREAD

**Issue by faulhaber** [PhiloBiblon/philobiblon-ui#125]
This is update of [issue#89](https://github.com/PhiloBiblon/philobiblon-ui/issues/89).

To test the problem of searching MAN, COP, and ANA, see
[BETA Manid 1119 (Madrid: Biblioteca Nacional de España, INC/766)](https://philobiblon.upf.edu/xtf/servlet/org.cdlib.xtf.dynaXML.DynaXML?source=unified/Display/1119BETA.MsEd.xml&style=MsEd.xsl%0A%0A%20%0A%20%0A%20&gobk=http%3A%2F%2Fphilobiblon.upf.edu%2Fxtf%2Fservlet%2Forg.cdlib.xtf.crossQuery.CrossQuery%3Frmode%3Dphilobeta%26mstype%3DP%26everyone%3D%26city%3D%26library%3D%26shelfmark%3Dinc%2F766%26daterange%3D%26placeofprod%3D%26scribe%3D%26publisher%3D%26prevowner%3D%26assocname%3D%26subject%3D%26text-join%3Dand%26browseout%3Dmsed%26sort%3Dtitle), linked to

[BETA manid 1119 (pb.cog)](https://philobiblon.cog.berkeley.edu/wiki/Item:Q37805) linked to
[BETA cnum 130 (pb.cog)](https://philobiblon.cog.berkeley.edu/wiki/Item:Q160) and to
[BETA copid 1030](https://philobiblon.cog.berkeley.edu/wiki/Item:Q29900)

The relation betwen MAN and ANA will be based on the shared manid: MANID in  MAN and TEXT_MANID in ANA.
In addition the search should look for TITLE in MAN and TEXT_TITLE in ANA

The relation betwen MAN and COP will be based on the shared manid: MANID in  MAN and TEXT_MANID in COP.
The search should look for RELATED_LIBID in both MAN and COP
In addition the search should look for OWNER_CALLNO and RELATED_LIB_CALLNO  in MAN and the same fields in COP

The following searches from the legacy web should be primary: CITY, LIBRARY, COLLECTION, SHELFMARK.
The other searches should be Advanced Searches: DATE, PLACE OF PRODUCTION, SCRIBE / PRINTER, PUBLISHER / PATRON, PREVIOUS OWNER, ASSOCIATED PERSON, SUBJECT.

Based on [issue#189](https://github.com/PhiloBiblon/philobiblon-ui/issues/89)

**Comment by jmformenti** [comment]
Duplicated #77
