### ISSUE TITLE
Show linked images

### ISSUE THREAD

**Issue by faulhaber** [PhiloBiblon/philobiblon-ui#126]
To test the problem of linked images, see:
[BETA manid 1110 (Madrid: Biblioteca Nacional de España, MSS/12793 V. 1)](https://philobiblon.upf.edu/xtf/servlet/org.cdlib.xtf.dynaXML.DynaXML?source=unified/Display/1110BETA.MsEd.xml&style=MsEd.xsl%0A%0A%20%0A%20%0A%20&gobk=http%3A%2F%2Fphilobiblon.upf.edu%2Fxtf%2Fservlet%2Forg.cdlib.xtf.crossQuery.CrossQuery%3Frmode%3Dphilobeta%26mstype%3DM%26everyone%3Dmanid+1110%26city%3D%26library%3D%26shelfmark%3D%26daterange%3D%26placeofprod%3D%26scribe%3D%26publisher%3D%26prevowner%3D%26assocname%3D%26subject%3D%26text-join%3Dand%26browseout%3Dmsed%26sort%3Dtitle)
The link to the [digital facsimile in the BNE ](https://bdh-rd.bne.es/viewer.vm?id=0000092652&page=1)is found in the INTERNET field
[BETA manid 1110 (pb.cog)](https://philobiblon.cog.berkeley.edu/wiki/Item:Q37796)

Based on [issue#189](https://github.com/PhiloBiblon/philobiblon-ui/issues/89)

**Comment by jmformenti** [comment]
Try to find a new way to display images in PBUI, proposal:
1. Check if the URL is a simple image, in that case display directly the image.
2. Otherwise, redirect to the URL.
