### ISSUE TITLE
To solve the problem of standardization of metadata placement

### ISSUE THREAD

**Issue by faulhaber** [PhiloBiblon/philobiblon-ui#128]
Problem: How to ensure that metadata and values always appear in the same order?
As a test case see Associated Persons in [Isabel I](https://philobiblon.cog.berkeley.edu/ui/item/Q22551).
The order should always be:
P299 (Subject has role) or P820 (Object has role)
P73 (Note)
P49 (Begin Date) 
P787 (Begin date Qualifier)
P50 (End Date)
P788 (End Date Qualifier{
P721 (Source)
The problem is that in many cases, probably most, one or more of these properties is missing in the data.
From "Juan de Escobedo" on down there is no consistency.

**Comment by faulhaber** [comment]
See also [issue#127](https://github.com/PhiloBiblon/philobiblon-ui/issues/127). The same problem of syn

**Comment by faulhaber** [comment]
I changed the following, as per your suggestion, in UI Sorted Properties:
P703 (Associated persons) RELATED_BIOID_SUBJECT_QNUMBER
qualifier P277 (Subject has role) RELATED_BIOCLASS_QNUMBER
qualifier P820 (Object has role) RELATED_BIOCLASS_QNUMBER

This solved the problem of the sorting order in PBUI, at least in BIO. See [Isabel I](https://philobiblon.cog.berkeley.edu/ui/es/item/Q22551). The first column in P703 now contains either P277 or P820.
It would be best if the spacing of the other columns was always the same. Right now it seems to reflect the presence or abasence of a given column

**Comment by jmformenti** [comment]
Fixed.
