### ISSUE TITLE
Consistent display of UI columns

### ISSUE THREAD

**Issue by austininseoul** [PhiloBiblon/philobiblon-ui#137]
https://philobiblon.cog.berkeley.edu/ui/item/Q22551

<img width="950" alt="Screenshot 2024-09-16 at 8 54 02 AM" src="https://github.com/user-attachments/assets/808c575c-cd27-4488-9481-9f4cdde08d58">
<img width="950" alt="Screenshot 2024-09-16 at 8 53 29 AM" src="https://github.com/user-attachments/assets/e00d9b79-8300-4f08-bc33-c8d30fcd07b9">

If you look at the screenshots, the columns are inconsistent and spaced according to each other, they should have a fixed width. Then for overflow you should be able to hover over to see the extras. Do this with a modal. Make the columns more like Google Sheets or Excel style. They should be compact and efficient. right now the ui is too spaced out. In addition, the Birth, Event, Related Place, Death, these shouldn't be values in a column. And just a label above the grid.

**Comment by jmformenti** [comment]
Example here #127

**Comment by jmformenti** [comment]
Check this case #147
