### ISSUE TITLE
Correlate qualifiers with values

### ISSUE THREAD

**Issue by faulhaber** [PhiloBiblon/philobiblon-ui#147]
[Correlate qualifiers with values is issue #99](https://github.com/PhiloBiblon/philobiblon-private/issues/99) in philobiblon-private. It's not clear whether this was ever an issue in philobiblon-ui.
See [Q5](https://philobiblon.cog.berkeley.edu/ui/item/Q42), where the correlation between the folio number of the incipit and explicit is hard to read.
This has to correlate P577 (physical description) (11ra, 219vb) with the values of incipit and explicit.
See legacy web page [CNUM 5](https://philobiblon.upf.edu/xtf/servlet/org.cdlib.xtf.dynaXML.DynaXML?source=/unified/Display/5BETA.AnalyticCopy.xml&style=AnalyticCopy.xsl&gobk=http%3A%2F%2Fphilobiblon.upf.edu%2Fxtf%2Fservlet%2Forg.cdlib.xtf.crossQuery.CrossQuery%3Frmode%3Dphilobeta%26everyone%3D%22cnum%205%22%26creator%3D%26title%3D%26incipit%3D%26explicit%3D%26assocname%3D%26daterange%3D%26placeofcomposition%3D%26subject%3D%26text-join%3Dand%26browseout%3Dwork%26sort%3Dmoniker)

**Comment by faulhaber** [comment]
I have done some fiddling with the schema for  https://github.com/PhiloBiblon/philobiblon-private/issues/99 by using two different properties as Max suggested, P577 (physical description for INCIPIT_LOC and P101 (Sort String) for EXPLICIT_LOC. See [Q40](https://philobiblon.cog.berkeley.edu/ui/item/Q40) and [Q135](https://philobiblon.cog.berkeley.edu/ui/item/Q135).
It solves the problem of the ordering. Now the PBUI has to be adjusted to account for spacing, word wrapping. PhiloBiblon_UI issue#147.
This is similar to issue

**Comment by jmformenti** [comment]
Related to #137
