### ISSUE TITLE
Move current PhiloBiblon's HTMLs to here

### ISSUE THREAD

**Issue by jmformenti** [PhiloBiblon/philobiblon-ui#3]
Each of the legacy Welcome screens has a set of secondary web pages:
[SEARCH](https://bancroft.berkeley.edu/philobiblon/search_en.html), [ABOUT PhiloBiblon](https://bancroft.berkeley.edu/philobiblon/about_en.html), [HELP](https://bancroft.berkeley.edu/philobiblon/help_en.html), 
[RESOURCES](https://bancroft.berkeley.edu/philobiblon/resources_en.html), [COLLABORATE](https://bancroft.berkeley.edu/philobiblon/collaborate_en.html).

PBUI already has placeholders for these pages at the bottom of the welcome page. SEARCH is already taken care of. ABOUT PhiloBiblon should be the first priority. It in turn has nine sub-pages: 1 [Bibliographies](https://bancroft.berkeley.edu/philobiblon/about_en.html),  2 [Preferred citation](https://bancroft.berkeley.edu/philobiblon/citation_en.html),  3 [Language](https://bancroft.berkeley.edu/philobiblon/language_en.html),  4 [Statistics](https://bancroft.berkeley.edu/philobiblon/statistics_en.html),  5 [Web version](https://bancroft.berkeley.edu/philobiblon/webversion_en.html),  6 [Windows version](https://bancroft.berkeley.edu/philobiblon/windowsversion_en.html),  7 [History](https://bancroft.berkeley.edu/philobiblon/history_en.html),  8 [Acknowledgments](https://bancroft.berkeley.edu/philobiblon/acknowledgments_en.html)
, 9 [Copyright](https://bancroft.berkeley.edu/philobiblon/copyright_en.html).

Work on these in the order given, but note that Copyright is a verbatim copy of Preferred Citation. Web version and Windows version will have to be extensively re-written, but it will be easier to that on PBUI.

The links will have to go to PBUI, not to the legacy web page.

**Comment by faulhaber** [comment]
@austininseoul: In addition to the internal links within the HELP pages, the internal links within the web pages of BETA, BITAGAP, and BITECA need to be fixed.
