### ISSUE TITLE
Add home pages for all languages

### ISSUE THREAD

**Issue by jmformenti** [PhiloBiblon/philobiblon-ui#72]
Currently, there is only a home page for the English language.
We need to create equivalent pages for the other languages: Català, Español, Galego, Português.

**Implementation Hints**
* For each language, add an entry here: https://philobiblon.cog.berkeley.edu/wiki/En_PhiloBiblonViewer_Index, like _en_Welcome_ for English.
* Translate the welcome page from https://bancroft.berkeley.edu/philobiblon/ to wiki page format, similar to the English page: https://philobiblon.cog.berkeley.edu/wiki/En_Welcome

**Definition of Done**
1. Check if the English welcome page is updated and update it if necessary.
2. Create a new welcome page for each language and verify its visualization in PBUI.

**Comment by faulhaber** [comment]
This is less important than adding the search filters for the various tables

**Comment by faulhaber** [comment]
Josep noted that in fact all of the Welcome pages for the other languages have also been finished.

**Comment by jmformenti** [comment]
Duplicated #3
