### ISSUE TITLE
Add search filters for Reference option

### ISSUE THREAD

**Issue by jmformenti** [PhiloBiblon/philobiblon-ui#76]
Same filters as: https://bancroft.berkeley.edu/philobiblon/searchreference_en.html

**Comment by jmformenti** [comment]
Pending consideration of the PUBLISHED_NOTE field in the date filter.

**Comment by faulhaber** [comment]
Josep: Ok but the problem is that we need to import PUBLISHED_NOTE_DATE (or other name) to wikibase as well in order to be available for the SPARQL query, so at the end it seems that PUBLISHED_NOTE and PUBLISHED_NOTE_DATE is quite redundant

**Comment by faulhaber** [comment]
I agree that both PUBLISHED_NOTE and PUBLISHED_NOTE_DATE need to be imported to Wikibase. I don't think that they are redundant. PUBLISHED_NOTE will give the raw data. This is what the user will see. PUBLISHED_NOTE_DATE  gives the cleaned data with canonical dates. This will serve as the basis for the SPARQL queries, but the user won't see the data except when using the DATE filter.  I assume that both will have to be listed in the schema and exported in the QS file.

**Comment by jmformenti** [comment]
Agreed not to create field PUBLISHED_NOTE_DATE for now
