### ISSUE TITLE
Add search filters for MsEd option

### ISSUE THREAD

**Issue by jmformenti** [PhiloBiblon/philobiblon-ui#77]
Same filters as: https://bancroft.berkeley.edu/philobiblon/searchmsed_en.html

**Comment by jmformenti** [comment]
Take into account relationships explained in issue [#118](https://github.com/PhiloBiblon/philobiblon-private/issues/118)

**Comment by faulhaber** [comment]
We need to wait on this until Max adds the additional Milestone columns
