### ISSUE TITLE
Add search filters for Geography option

### ISSUE THREAD

**Issue by jmformenti** [PhiloBiblon/philobiblon-ui#78]
TODO review with @faulhaber  the filters to add

**Comment by faulhaber** [comment]
For GEO we need a filter for TYPE (e.g., city, county, diocese) and CLASS (e.g., geographical, political, ecclesiastical

**Comment by faulhaber** [comment]
I have been rethinking this. What users want to be able to find are geographical places, like City, State, and Nation. I therefore do not think we need a Class filter. We do need a Type filter, but it should be called simply "Place" In Spanish "Lugar" I have moved this up as a priority.
