### ISSUE TITLE
Add search filters for Subject option

### ISSUE THREAD

**Issue by jmformenti** [PhiloBiblon/philobiblon-ui#79]
TODO review with @faulhaber the filters to add

**Comment by faulhaber** [comment]
We should filter by the bibliography, i.e, BETA, BITECA, and BITAGAP. and All,
In terms of what to display, the Label will be the Moniker. The other fields to display are those in the app: 
Variant Headings, Does not need Variant_Heading Class nor any of the other qualifiers
Broader Headings,
Related_Bibliography
Notes'
Internet

We do not need Related_MsEd

**Comment by faulhaber** [comment]
We need to have the exact equivalent of the FactGrid searchbox, so that as the user starts typing the possible objects start to appear
