### ISSUE TITLE
[TO REFINE] Adapt analytic items visualization

### ISSUE THREAD

**Issue by jmformenti** [PhiloBiblon/philobiblon-ui#89]
Analytic items (i.e., _cnum_) do not have a specific entry in the PBUI menu but are related to other item types and therefore need to be displayed. Here are the relationships I found between analytics and works/manuscripts:
```
1 manid - (1 - n) -> cnum - (1 - 1) -> texid
1 texid - (1 - n) -> cnum
```
An example of the relationship between _manid_ and _cnum_ can be found in [BITECA manid 1988](https://philobiblon.upf.edu/xtf/servlet/org.cdlib.xtf.dynaXML.DynaXML?source=unified/Display/1988BITECA.MsEd.xml&style=MsEd.xsl%0A%0A%20%0A%20%0A%20&gobk=http%3A%2F%2Fphilobiblon.upf.edu%2Fxtf%2Fservlet%2Forg.cdlib.xtf.crossQuery.CrossQuery%3Frmode%3Dphilo%26everyone%3Dalfonso%26city%3D%26library%3D%26shelfmark%3D%26daterange%3D%26placeofprod%3D%26scribe%3D%26publisher%3D%26prevowner%3D%26assocname%3D%26subject%3D%26text-join%3Dand%26browseout%3Dmsed%26sort%3Dtitle) on the current PhiloBiblon website. In the current website, for each directly related _cnum_, the information of the _cnum_ is shown, along with the link to the item.

The same applies to items of type _copid_.

Therefore, we should add new functionality to preview the information of certain items. Currently, this seems to apply to _cnum_ and _copid_ items.

We could potentially visualize this with expandable panels: https://v2.vuetifyjs.com/en/components/expansion-panels/#usage

**Comment by faulhaber** [comment]
CNUM and COPID are the only items where this problem occurs.

**Comment by donaldziff** [comment]
1. To test the problem of searching UNI and ANA, see:

[BETA texid 1029 (Alfonso X, Siete partidas)](https://philobiblon.upf.edu/xtf/servlet/org.cdlib.xtf.dynaXML.DynaXML?source=unified/Display/1029BETA.Work.xml&style=Work.xsl%0A%0A%20%0A%20%0A%20&gobk=http%3A%2F%2Fphilobiblon.upf.edu%2Fxtf%2Fservlet%2Forg.cdlib.xtf.crossQuery.CrossQuery%3Frmode%3Dphilobeta%26everyone%3Dtexid+1029%26creator%3D%26title%3D%26incipit%3D%26explicit%3D%26assocname%3D%26daterange%3D%26placeofcomposition%3D%26subject%3D%26text-join%3Dand%26browseout%3Dwork%26sort%3Dmoniker)
[BETA texid 1029 (pb.cog)](https://philobiblon.cog.berkeley.edu/wiki/Item:Q43297) linked to
[BETA cnum 130 (pb.cog)](https://philobiblon.cog.berkeley.edu/wiki/Item:Q160)

2. To test the problem of searching MAN, ANA, and COP, see

[BETA Manid 1119 (Madrid: Biblioteca Nacional de España, INC/766)](https://philobiblon.upf.edu/xtf/servlet/org.cdlib.xtf.dynaXML.DynaXML?source=unified/Display/1119BETA.MsEd.xml&style=MsEd.xsl%0A%0A%20%0A%20%0A%20&gobk=http%3A%2F%2Fphilobiblon.upf.edu%2Fxtf%2Fservlet%2Forg.cdlib.xtf.crossQuery.CrossQuery%3Frmode%3Dphilobeta%26mstype%3DP%26everyone%3D%26city%3D%26library%3D%26shelfmark%3Dinc%2F766%26daterange%3D%26placeofprod%3D%26scribe%3D%26publisher%3D%26prevowner%3D%26assocname%3D%26subject%3D%26text-join%3Dand%26browseout%3Dmsed%26sort%3Dtitle), linked to

BETA manid 1119  (pb.cog) linked to
[BETA cnum 130 (pb.cog)](https://philobiblon.cog.berkeley.edu/wiki/Item:Q160) and to
[BETA copid 1030](https://philobiblon.cog.berkeley.edu/wiki/Item:Q29900)

3. To test the problem of linked images, see:

[BETA manid 1110 (Madrid: Biblioteca Nacional de España, MSS/12793 V. 1)](https://philobiblon.upf.edu/xtf/servlet/org.cdlib.xtf.dynaXML.DynaXML?source=unified/Display/1110BETA.MsEd.xml&style=MsEd.xsl%0A%0A%20%0A%20%0A%20&gobk=http%3A%2F%2Fphilobiblon.upf.edu%2Fxtf%2Fservlet%2Forg.cdlib.xtf.crossQuery.CrossQuery%3Frmode%3Dphilobeta%26mstype%3DM%26everyone%3Dmanid+1110%26city%3D%26library%3D%26shelfmark%3D%26daterange%3D%26placeofprod%3D%26scribe%3D%26publisher%3D%26prevowner%3D%26assocname%3D%26subject%3D%26text-join%3Dand%26browseout%3Dmsed%26sort%3Dtitle)
The link to the [digital facsimile in the BNE ](https://bdh-rd.bne.es/viewer.vm?id=0000092652&page=1)is found in the INTERNET field
BETA manid 1110  (pb.cog)

4. To test the problem of synching metadata and data in the display screens, see

[BETA manid 1001 (Madrid: Biblioteca Nacional de España, MSS/9477)](https://philobiblon.upf.edu/xtf/servlet/org.cdlib.xtf.dynaXML.DynaXML?source=unified/Display/1001BETA.MsEd.xml&style=MsEd.xsl%0A%0A%20%0A%20%0A%20&gobk=http%3A%2F%2Fphilobiblon.upf.edu%2Fxtf%2Fservlet%2Forg.cdlib.xtf.crossQuery.CrossQuery%3Frmode%3Dphilobeta%26mstype%3DM%26everyone%3Dmanid+1001%26city%3D%26library%3D%26shelfmark%3D%26daterange%3D%26placeofprod%3D%26scribe%3D%26publisher%3D%26prevowner%3D%26assocname%3D%26subject%3D%26text-join%3Dand%26browseout%3Dmsed%26sort%3Dtitle).
BETA manid 1001  (pb.cog)
Note particularly Date of Artifact and compare it to the treatment in the legacy web.

**Comment by donaldziff** [comment]
@jmformenti please evaluate whether this issue is unblocked

**Comment by donaldziff** [comment]
@jmformenti @faulhaber break this down into separate issues

**Comment by jmformenti** [comment]
The task of displaying analytical elements has been split into two tasks: #142 #143
